apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: u95gdbyq4-java-springboot
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe:cfa6aa1053d8032b68ce9828154c0f4aac66121e@sha256:0117fc6afb2cce60bdebd3ce79c773625490ef58b75ae1badc686ca583f2a260
          name: container-image
